title:             Yong의 개발블로그
email:             yongdev91@gmail.com
description:       Yong의 개발블로그
author:            Yong
baseurl:           ""
url:               "http://yongdev91.github.io"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   yongdev91
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
