title:             Yong Blog
email:             ///
description:       A Blog Theme by Start Bootstrap
author:            Start Bootstrap
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://yongdev91.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
